"""add soft delete columns to project_submissions

Revision ID: 277edc2dad66
Revises: a1b2c3d4e5f6
Create Date: 2026-04-20 15:45:45.920546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277edc2dad66'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pre_approved_students', ['id'])
    op.add_column('project_submissions', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('project_submissions', sa.Column('deleted_by_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_submissions', 'deleted_by_admin')
    op.drop_column('project_submissions', 'is_deleted')
    op.drop_constraint(None, 'pre_approved_students', type_='unique')
    # ### end Alembic commands ###
