"""Add missing columns to StudentAuth

Revision ID: 3b9acc898ae3
Revises: 50ec7eadef66
Create Date: 2026-04-08 15:04:36.166601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9acc898ae3'
down_revision: Union[str, Sequence[str], None] = '50ec7eadef66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'evaluation_criterion_scores', ['id'])
    op.create_unique_constraint(None, 'evaluations', ['id'])
    op.create_unique_constraint(None, 'faculty', ['id'])
    op.create_unique_constraint(None, 'integrity_flags', ['id'])
    op.create_unique_constraint(None, 'member_evaluations', ['id'])
    op.create_unique_constraint(None, 'project_submissions', ['id'])
    op.add_column('studentauth', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'studentauth', ['id'])
    op.create_unique_constraint(None, 'team_memberships', ['id'])
    op.create_unique_constraint(None, 'viva_questions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viva_questions', type_='unique')
    op.drop_constraint(None, 'team_memberships', type_='unique')
    op.drop_constraint(None, 'studentauth', type_='unique')
    op.drop_column('studentauth', 'is_verified')
    op.drop_constraint(None, 'project_submissions', type_='unique')
    op.drop_constraint(None, 'member_evaluations', type_='unique')
    op.drop_constraint(None, 'integrity_flags', type_='unique')
    op.drop_constraint(None, 'faculty', type_='unique')
    op.drop_constraint(None, 'evaluations', type_='unique')
    op.drop_constraint(None, 'evaluation_criterion_scores', type_='unique')
    # ### end Alembic commands ###
