"""Initial migration: Create all tables

Revision ID: 50ec7eadef66
Revises: 
Create Date: 2026-04-03 22:54:54.449553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ec7eadef66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FACULTY', name='facultyrole'), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_faculty_email'), 'faculty', ['email'], unique=True)
    op.create_table('studentauth',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enrollment_no', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('programme', sa.Enum('BTECH', 'MTECH', 'MCA', 'PHD', name='programmetype'), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_studentauth_email'), 'studentauth', ['email'], unique=True)
    op.create_index(op.f('ix_studentauth_enrollment_no'), 'studentauth', ['enrollment_no'], unique=True)
    op.create_table('project_submissions',
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=True),
    sa.Column('phase_1_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phase_2_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_phase', sa.Enum('PHASE_1', 'PHASE_2', 'FINAL', 'SUBMITTED', name='projectphase'), nullable=False),
    sa.Column('guide_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='guidestatus'), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['studentauth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_project_submissions_team_id'), 'project_submissions', ['team_id'], unique=True)
    op.create_table('evaluations',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('PHASE_1', 'PHASE_2', 'FINAL', name='evaluationphase'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='evaluationstatus'), nullable=False),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('agent_trace_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('team_memberships',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('functions', sa.Text(), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['studentauth.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['project_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('evaluation_criterion_scores',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('integrity_flags',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('SIMILARITY', 'STYLE_SHIFT', 'CODE_JUMP', 'AI_GENERATED', 'CONTRIBUTION_MISMATCH', name='integrityflagtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='integrityseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('member_evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('contribution_score', sa.Float(), nullable=False),
    sa.Column('technical_depth', sa.Float(), nullable=False),
    sa.Column('code_quality', sa.Float(), nullable=False),
    sa.Column('documentation', sa.Float(), nullable=False),
    sa.Column('overall_member_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('alignment_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['team_memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('viva_questions',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('member_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['member_evaluation_id'], ['member_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viva_questions')
    op.drop_table('member_evaluations')
    op.drop_table('integrity_flags')
    op.drop_table('evaluation_criterion_scores')
    op.drop_table('team_memberships')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_project_submissions_team_id'), table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index(op.f('ix_studentauth_enrollment_no'), table_name='studentauth')
    op.drop_index(op.f('ix_studentauth_email'), table_name='studentauth')
    op.drop_table('studentauth')
    op.drop_index(op.f('ix_faculty_email'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
