"""add_has_viewed_feedback_to_membership

Revision ID: 62e3130710f8
Revises: dab9b38b52f6
Create Date: 2026-06-07 16:52:05.442312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e3130710f8'
down_revision: Union[str, Sequence[str], None] = 'dab9b38b52f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.add_column('team_memberships', sa.Column('has_viewed_feedback', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_memberships', 'has_viewed_feedback')
    op.drop_constraint(None, 'notifications', type_='unique')
    # ### end Alembic commands ###
