"""add interview to evaluationphase enum

Revision ID: dab9b38b52f6
Revises: c9ff35ee616f
Create Date: 2026-06-03 16:27:22.165857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab9b38b52f6'
down_revision: Union[str, Sequence[str], None] = 'c9ff35ee616f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE evaluationphase ADD VALUE IF NOT EXISTS 'INTERVIEW'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum values cannot be easily removed in PostgreSQL without recreating the type.
    # We leave this blank or implement a complex migration if strictly required.
    pass
    # ### end Alembic commands ###
