"""add_admin_and_whitelist_v2

Revision ID: e64a7c4732b3
Revises: 3b9acc898ae3
Create Date: 2026-04-19 11:17:09.502702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e64a7c4732b3'
down_revision: Union[str, Sequence[str], None] = '3b9acc898ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create adminstatus enum explicitly
    admin_status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='adminstatus')
    admin_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('pre_approved_students',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enrollment_no', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('programme', postgresql.ENUM('BTECH', 'MTECH', 'MCA', 'PHD', name='programmetype', create_type=False), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pre_approved_students_email'), 'pre_approved_students', ['email'], unique=True)
    op.create_index(op.f('ix_pre_approved_students_enrollment_no'), 'pre_approved_students', ['enrollment_no'], unique=True)
    op.add_column('faculty', sa.Column('specialization', sa.String(length=255), nullable=True))
    op.add_column('project_submissions', sa.Column('admin_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='adminstatus'), nullable=False, server_default='PENDING'))
    op.add_column('project_submissions', sa.Column('admin_feedback', sa.Text(), nullable=True))
    op.add_column('team_memberships', sa.Column('work_description', sa.Text(), nullable=True))
    op.add_column('team_memberships', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('team_memberships', sa.Column('ai_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_memberships', 'ai_feedback')
    op.drop_column('team_memberships', 'tech_stack')
    op.drop_column('team_memberships', 'work_description')
    op.drop_column('project_submissions', 'admin_feedback')
    op.drop_column('project_submissions', 'admin_status')
    op.drop_column('faculty', 'specialization')
    op.drop_index(op.f('ix_pre_approved_students_enrollment_no'), table_name='pre_approved_students')
    op.drop_index(op.f('ix_pre_approved_students_email'), table_name='pre_approved_students')
    op.drop_table('pre_approved_students')
    # ### end Alembic commands ###
